services:
  db:
    image: postgres:latest
    container_name: proyecto-backend-mure-dev
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5433:5432"
