services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    container_name: proyecto-backend-mure-dev
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
